[tools]
shellspec  = 'latest'
shellcheck = 'latest'
pre-commit = 'latest'
semver     = 'latest'
jq         = 'latest'
trufflehog = 'latest'

[plugins]
trufflehog = 'https://github.com/Inetum-Poland/asdf-trufflehog.git'

[settings]
not_found_auto_install = true
