name: 'bumper - Bump version when merging Pull Request with specific labels. Bump versions on tag push.'
description: 'Bump version when merging Pull Request with specific labels (bumper:major, bumper:minor, bumper:patch, bumper:none)'
author: 'Inetum-Poland'

inputs:
  bump_default_level:
    description: "Default bump level if labels are not attached [major,minor,patch]. Do nothing if it's empty"
    required: false
  bump_fail_if_no_level:
    description: "Fail if no bump label is found"
    required: false
    default: "false"
  bump_include_v:
    description: "Whether to include v in tag name"
    required: false
    default: "true"
  bump_latest:
    description: "Whether to add `latest` tag"
    required: false
    default: "false"
  bump_major:
    description: "Label name for major bump (bump:major)"
    required: false
    default: "bumper:major"
  bump_minor:
    description: "Label name for minor bump (bump:minor)"
    required: false
    default: "bumper:minor"
  bump_none:
    description: "Label name for no bump (bump:none)"
    required: false
    default: "bumper:none"
  bump_patch:
    description: "Label name for patch bump (bump:patch)"
    required: false
    default: "bumper:patch"
  bump_semver:
    description: "Whether to updates major/minor release tags on a tag push. e.g. Update `v1` and `v1.2` tag when released `v1.2.3`."
    required: false
    default: "false"
  bump_tag_as_email:
    description: "Email address to use when creating tags"
    required: false
  bump_tag_as_user:
    description: "Name to use when creating tags"
    required: false
  github_token:
    description: 'GITHUB_TOKEN to list pull requests and create tags'
    required: true
    default: '${{ github.token }}'

outputs:
  current_version:
    description: "The current version before any changes"
  next_version:
    description: "The next version after any changes"
  skip:
    description: "True if release is skipped. e.g. No labels attached to PR."
  message:
    description: "Tag message"
  tag_status:
    description: "Tag status"

runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'tag'
  color: 'green'
