name: 'bumper - Bump version when merging Pull Request with specific labels. Bump versions on tag push.'
description: 'Bump version when merging Pull Request with specific labels (bumper:major, bumper:minor, bumper:patch, bumper:none)'
author: 'Inetum-Poland'

inputs:
  add_latest: { description: "Whether to add `latest` tag", required: false, default: "false" }
  bump_major: { description: "Label name for major bump (bump:major)", required: false, default: "bumper:major" }
  bump_minor: { description: "Label name for minor bump (bump:minor)", required: false, default: "bumper:minor" }
  bump_none: { description: "Label name for no bump (bump:none)", required: false, default: "bumper:none" }
  bump_patch: { description: "Label name for patch bump (bump:patch)", required: false, default: "bumper:patch" }
  bump_semver: { description: "Whether to updates major/minor release tags on a tag push. e.g. Update `v1` and `v1.2` tag when released `v1.2.3`.", required: false, default: "false" }
  default_bump_level: { description: "Default bump level if labels are not attached [major,minor,patch]. Do nothing if it's empty", required: false }
  dry_run: { description: "Do not actually tag next version if it's true", required: false }
  fail_if_no_bump: { description: "Fail if no bump label is found", required: false, default: "false" }
  github_token: { description: 'GITHUB_TOKEN to list pull requests and create tags', required: true, default: '${{ github.token }}' }
  include_v: { description: "Whether to include v in tag name", required: false, default: "true" }
  tag_as_email: { description: "Email address to use when creating tags", required: false }
  tag_as_user: { description: "Name to use when creating tags", required: false }

outputs:
  current_version:
    description: "The current version before any changes"
    value: ${{ steps.action_bumper.outputs.current_version }}
  next_version:
    description: "The next version after any changes"
    value: ${{ steps.action_bumper.outputs.next_version }}
  skip:
    description: "True if release is skipped. e.g. No labels attached to PR."
    value: ${{ steps.action_bumper.outputs.skip }}
  message:
    description: "Tag message"
    value: ${{ steps.action_bumper.outputs.message }}
  tag_status:
    description: "Tag status"
    value: ${{ steps.action_bumper.outputs.tag_status }}

runs:
  using: "composite"
  steps:
    - run: |
        sudo apt update
        sudo apt install -y jq curl git bash
        curl https://mise.run | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
      shell: bash

    - run: |
        mise install
      shell: bash

    - uses: jwalton/gh-find-current-pr@v1
      if: ${{ !github.event.act }} # skip during local actions testing
      id: finder

    - id: action_bumper
      run: ${{ github.action_path }}/action_bumper.sh
      shell: bash
      env:
        INPUT_ADD_LATEST: ${{ inputs.add_latest }}
        INPUT_BUMP_MAJOR: ${{ inputs.bump_major }}
        INPUT_BUMP_MINOR: ${{ inputs.bump_minor }}
        INPUT_BUMP_NONE: ${{ inputs.bump_none }}
        INPUT_BUMP_PATCH: ${{ inputs.bump_patch }}
        INPUT_BUMP_SEMVER: ${{ inputs.bump_semver }}
        INPUT_DEFAULT_BUMP_LEVEL: ${{ inputs.default_bump_level }}
        INPUT_FAIL_IF_NO_BUMP: ${{ inputs.fail_if_no_bump }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_INCLUDE_V: ${{ inputs.include_v }}
        INPUT_TAG_AS_EMAIL: ${{ inputs.tag_as_email }}
        INPUT_TAG_AS_USER: ${{ inputs.tag_as_user }}

    - uses: marocchino/sticky-pull-request-comment@v2
      if: always() && (steps.action_bumper.outputs.tag_status != null) && (steps.finder.outputs.pr != null) && ${{ !github.event.act }}
      with:
        header: action-bumper
        number: ${{ steps.finder.outputs.pr }}
        message: ${{ steps.action_bumper.outputs.tag_status }}

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'tag'
  color: 'green'
