# Copyright (c) 2024 Inetum Poland.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  bumper:
    runs-on: ubuntu-latest
    env:
      INETUM_POLAND_ACTION_BUMPER_DEBUG: ${{ vars.INETUM_POLAND_ACTION_BUMPER_DEBUG }}
      INETUM_POLAND_ACTION_BUMPER_TRACE: ${{ vars.INETUM_POLAND_ACTION_BUMPER_TRACE }}
    steps:
      - uses: hmarr/debug-action@v3

      - uses: actions/checkout@v5

      - uses: jwalton/gh-find-current-pr@v1
        id: finder
        with:
          state: all

      - id: bumper
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bump_fail_if_no_level: true
          bump_semver: true
          bump_latest: true

      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.bumper.outputs.tag_status != null) && (steps.finder.outputs.pr != null) && (steps.bumper.outputs.skip != true)
        with:
          header: bumper
          number: ${{ steps.finder.outputs.pr }}
          message: ${{ steps.bumper.outputs.tag_status }}

      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.bumper.outputs.tag_status == null || steps.bumper.outputs.skip == true)
        with:
          header: bumper
          delete: true

      #TODO(aamkye): Releaser
