on:
  push:
    branches:
      - main
    #! This could be added in the future as a proper use-case would be found.
    # tags:
    #   - 'v?*.*.*'
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  tag_bumper:
    runs-on: ubuntu-latest
    env:
      INETUM_POLAND_ACTION_BUMPER_DEBUG: ${{ vars.INETUM_POLAND_ACTION_BUMPER_DEBUG }}
      INETUM_POLAND_ACTION_BUMPER_TRACE: ${{ vars.INETUM_POLAND_ACTION_BUMPER_TRACE }}
    steps:
      - uses: hmarr/debug-action@v3

      - uses: actions/checkout@v4

      - uses: jwalton/gh-find-current-pr@v1
        id: finder
        with:
          state: all

      - id: bumper
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bump_fail_if_no_level: true
          bump_semver: true
          bump_latest: true

      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.bumper.outputs.tag_status != null) && (steps.finder.outputs.pr != null)
        with:
          header: action-bumper
          number: ${{ steps.finder.outputs.pr }}
          message: ${{ steps.bumper.outputs.tag_status }}
